language: cpp
compiler: gcc
before_install:
 - "sudo apt-get update -qq"
 - "sudo apt-get install -qq autoconf libgtk2.0-dev libdbus-glib-1-dev libtag1-dev libgstreamer-plugins-base0.10-dev zip unzip gstreamer0.10-plugins-base gstreamer0.10-plugins-good gstreamer0.10-plugins-bad gstreamer0.10-plugins-ugly gstreamer0.10-ffmpeg gtk2-engines-pixbuf"
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
install:
 - "echo 'ac_add_options --with-media-core=gstreamer' >> nightingale.config"
 - "echo 'ac_add_options --with-taglib-source=packaged' >> nightingale.config"
script: "./build.sh
branches:
  only:
  - master-xul-9.0.1
notifications:
  email:
    on_success: change
    on_failure: change
  irc: "irc.mozilla.org#nightingale"
